#!/usr/bin/env node
/*
 * Generate data/pinyin.js — the Mandarin-pinyin index the search box uses.
 *
 * WHY THIS EXISTS
 * The family's English names are Hakka ("Nyiap Len", "Fui Chung", "Yit Sin"), so a
 * relative who only knows Mandarin pinyin types "ye" and finds nothing, even though
 * 業 is right there. This file lets the search read the Chinese characters and match
 * their Mandarin readings too. It also makes 业 find 業 for free, because both sides
 * are compared as pinyin rather than as characters.
 *
 * SHAPE
 *   window.PY_GROUPS = { "ye": "業业夜葉…", "hui": "惠會…", … }
 * Grouped by syllable rather than char→pinyin because it stores the same information
 * with a fraction of the JSON punctuation: ~74 KB raw, ~53 KB gzipped for the whole
 * CJK block. js/app.js loads it lazily, the first time someone types in the search
 * box, so browsing costs nothing.
 *
 * A character appears under EVERY reading it has (up to 4), so 樂 is found by both
 * "le" and "yue" — worth it for names, where the surname reading is often the rarer
 * one (曾 ceng/zeng, 區 qu/ou, 解 jie/xie).
 *
 * RUNNING IT (only needed when you want to refresh the table; the output is committed)
 *   cd /tmp && npm pack pinyin-pro@3.26.0 && tar xzf pinyin-pro-3.26.0.tgz
 *   node tools/gen_pinyin.js /tmp/package/dist/index.js
 */

const fs = require("fs");
const path = require("path");

const dist = process.argv[2];
if (!dist) {
  console.error("usage: node tools/gen_pinyin.js <path-to-pinyin-pro/dist/index.js>");
  console.error("see the header of this file for how to fetch pinyin-pro");
  process.exit(1);
}

const { pinyin } = require(path.resolve(dist));

const START = 0x4e00, END = 0x9fff;   // CJK Unified Ideographs — covers traditional and simplified
const MAX_READINGS = 4;

const groups = {};
let slots = 0;
for (let cp = START; cp <= END; cp++) {
  const ch = String.fromCodePoint(cp);
  let readings;
  try {
    readings = pinyin(ch, { toneType: "none", multiple: true, type: "array" });
  } catch (_) { continue; }
  if (!readings || !readings.length) continue;
  const seen = new Set();
  for (const r of readings.slice(0, MAX_READINGS)) {
    if (!/^[a-z]+$/.test(r) || seen.has(r)) continue;
    seen.add(r);
    (groups[r] = groups[r] || []).push(ch);
    slots++;
  }
}

const out = {};
Object.keys(groups).sort().forEach(k => { out[k] = groups[k].join(""); });

const header = `/* GENERATED by tools/gen_pinyin.js — do not edit by hand.
 * Mandarin readings, grouped by toneless syllable, for matching search queries
 * against Chinese names. See the tool's header for why and how to regenerate. */\n`;
const js = header + "window.PY_GROUPS=" + JSON.stringify(out) + ";\n";

const dest = path.join(__dirname, "..", "data", "pinyin.js");
fs.writeFileSync(dest, js);
console.log(`wrote ${path.relative(process.cwd(), dest)} — ` +
  `${Object.keys(out).length} syllables, ${slots} readings, ${(Buffer.byteLength(js) / 1024).toFixed(1)} KB`);
